apiVersion: v1
kind: Pod
metadata:
  name: skdemo-liveness
spec:
  containers:
    - image: matija94/kubernetes-demo-spring
      name: skdemo
      livenessProbe:
        httpGet:
          path: /liveness/
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 3
        failureThreshold: 2
