apiVersion: v1
kind: ReplicationController
metadata:
  name: skdemo-rc
spec:
  replicas: 3
  selector:
    app: skdemo
  template:
    metadata:
      labels:
        app: skdemo
    spec:
      containers:
        - name: skdemo
          image: matija94/kubernetes-demo-spring
          ports:
            - containerPort: 8080